### ISSUE TITLE
Help with setup the domain in server_name seafile.example.com

### ISSUE THREAD

**Issue by mikebgrep** [ChatDeBlofeld/seafile-arm-docker#11]
I am new to SWAG I heard it from this repository and i don't understand it.When i follow the steps everything look good but on the part with enter your domain I am confused what domain I need to enter I want to access the Seafile from my network or from outside network (if possible) so my question is I need to have registered domain to use the service or I can add local network address like ```192.168.1.60``` and access the server and the hub from it because I try and its not found.
Sorry again for this question but if this happen will be great.

**Comment by ChatDeBlofeld** [comment]
Hi, think about the SWAG container as a web server with automated TLS stuff inside. So, yes, if you want to use it, you'll need a registered domain (national TLD are usually cheap, you can even get some for free like .tk). That's for access from outside network.

For a **local network** access, follow the _no swag_ part in the readme. Here are the changes you need to make:

`.env` 
```
NO_SWAG=1
HOST=192.168.1.60
USE_HTTPS=0
```

`nginx/seafile.noswag.conf`
```
server_name 192.168.1.60;
```

Then `./compose.sh down -v && ./compose.sh up -d` and it should work (from local network): http://192.168.1.60

**Comment by mikebgrep** [comment]
This works . I have another question, how can I mount an external SSD to the sea file to store data there as I see the current storage space is 500kb. I look some examples online but not sure if its the right way.
Thank you again.

**Comment by ChatDeBlofeld** [comment]
What do you mean by "current storage space is 500kb" ? This is insanely small, even on a Pi or Pi-like board.

Anyway, you can find [here](https://raspberrypi-guide.github.io/filesharing/mounting-external-drive) a guide to mount an external drive.

Then, suppose your mount point is `/mnt/external_ssd`, you'll need to remap the docker volumes to somewhere in this directory. The only volume actually big enough to be worry about is currently mapped to a directory named `seafile-data` in your installation folder. Thus:

1. `./compose.sh down`
1. Move the `seafile-data` folder to somewhere on the external drive, let's say `/mnt/external_ssd/seafile/seafile-data`
2. Edit your `.env` to set the new location, something like `SEAFILE_DATA_DIR=/mnt/external_ssd/seafile/seafile-data`
3. `./compose.sh up -d`

**Comment by mikebgrep** [comment]
Again thank you this is what I was needed. I am new to docker, only know to pull images. You have star from me for the repository.
The best solution found I try a couple of others method to deploy Seafile and this is the best one.

**Comment by mikebgrep** [comment]
Hi again I have a question, I made a couple of things 
1. I try to import the container into CasaOS and I get second container with same name and the old change his name
2. I delete the imported container  and rename the old container, how was it was  been.
3. I start the old container from Portainer

Result: Now I didn't see my Libraries and folders which I sync. The folder for the drive is still in the external drive, but in seafile nothing is shown. I try now with compose.sh to stop the  server and go back live but still no folders and libraries

**Comment by mikebgrep** [comment]
I have a problem again, I log in into seafile and nothing shows.I reinstall and follow the same steps when i leave the folder in seafile install directory is ok but when I move it to external drive which is mounted I don't see anything. From ` you'll need to remap the docker volumes to somewhere in this directory.` what you mean I don't remember how I was do this. Its appear after reboot of the pi the external drive got unmount, probably.

**Comment by mikebgrep** [comment]
I fix it in a couple of tries but what if again the external SSD unmount if I mount it again do i will have access to the files

**Comment by ChatDeBlofeld** [comment]
Hi, what I mean by *remap volumes* is that if you move data on the host, you have to say docker how to find them again.

Let's say you have your data in `/home/pi/seafile/seafile-data` and you want to move them to `/mnt/ssd/seafile/seafile-data`. So you can use `mv` to move the folder `mv /home/pi/seafile/seafile-data /mnt/ssd/seafile`. But now how can docker know where your data were moved? It can't. In any way. Thus you have to specify the new location somewhere. The *somewhere* in this case is your `.env`. What was then `SEAFILE_DATA_DIR=/home/pi/seafile/seafile-data` becomes now `SEAFILE_DATA_DIR=/mnt/ssd/seafile/seafile-data`.

Note that you won't need to remap anything if you've edited the `.env` *before* first run.

> I fix it in a couple of tries but what if again the external SSD unmount if I mount it again do i will have access to the files

The files won't be lost if the drive is mounted again. You'll probably need to restart the containers though.

To mount the drive at boot, have a look at [this part](https://raspberrypi-guide.github.io/filesharing/mounting-external-drive#set-up-automatic-mounting) of the guide I previously mentioned.

**Comment by mikebgrep** [comment]
Yes I mapped as in your example and setup the ssd to mount on star of the pi I will see on reboot if they will be visible in seafile or I will need to restart the container.Anyway hood work and thank you for the help.

**Comment by mikebgrep** [comment]
Hi, @ChatDeBlofeld how are you?
I was forced to upgrade my os and I install everything from 0.Now I don't see the libraries and files when I set the path to the data folder to the external storage mapped folder from the previous setup.
Any ideas why this happen.

**Comment by ChatDeBlofeld** [comment]
Hi, what's the output of `df -h`? And what's the content of your `.env` (with credentials redacted)?

**Comment by mikebgrep** [comment]
This is the .env file.
The think is there that the folder ``SEAFILE_DATA_DIR=/mnt/exdisk/seafile`` was containing all the data before I deleted it when it was not displayed in the seafile
I am wondering now if I can use the seafile in the future. If I change the main storage, I can't load the data in the folder in the app.

Is there I miss something the sqlite file was in the same folder, but I don't manage to log in with the old user I created new.


```
### Compose parameters
# 0: SQLite | 1: MariaDB | 2: MySQL
DBMS=0
NOSWAG=1
# Port on which the noswag nginx container is listening
# You don't have to bother about this if you use the swag ver
sion
NOSWAG_PORT=80
# Full path of the Seafile image
SEAFILE_IMAGE=franchetti/seafile-arm
### Run parameters
PUID=1000
PGID=1000
TZ=Europe/Sofia
### Init parameters
HOST=192.168.100.14
# Leave empty for 80/443
PORT=
SEAFILE_ADMIN_EMAIL=email
SEAFILE_ADMIN_PASSWORD=password 
USE_HTTPS=0
# You don't have to bother about this if you use SQLite
MYSQL_HOST=db
MYSQL_USER_PASSWD=secret
MYSQL_ROOT_PASSWD=secret
### Volume parameters
SEAFILE_CONF_DIR=./seafile/conf
SEAFILE_LOGS_DIR=./seafile/logs
SEAFILE_DATA_DIR=/mnt/exdisk/seafile/
SEAFILE_SEAHUB_DIR=./seafile/seahub-data
# SQLite/MariaDB/MySQL data dir
DATABASE_DIR=./db
# You don't have to bother about this if you use the noswag v
ersion
SWAG_DIR=./swag
```

**Comment by mikebgrep** [comment]
Does ``DATABASE_DIR=./db`` play a role 🤔  I didn't manage to find this folder in the container.

**Comment by ChatDeBlofeld** [comment]
Not sure to understand where are your data now. You should just update the `SEAFILE_DATA_DIR` variable with the current path. ^^

> Does DATABASE_DIR=./db play a role 🤔 I didn't manage to find this folder in the container.

In the container it's mapped to `/shared/sqlite`. On the host, it's a `db` folder in the folder of the compose files. Much needed directory. If you didn't backup it when you reinstalled the host, well, you'll need to use [seaf-fsck](https://manual.seafile.com/latest/maintain/seafile_fsck/#exporting-libraries-to-file-system) to get your data back and upload everything again.

**Comment by mikebgrep** [comment]
This makes sense. I will check to backup, and this folder and use it if I migrate again should work.
Thanks

**Comment by mikebgrep** [comment]
I am closing the issue. Thanks for the help much clear now.
