### ISSUE TITLE
Unable to create containers

### ISSUE THREAD

**Issue by ShawnTheShadow** [ChatDeBlofeld/seafile-arm-docker#2]
So i follow all steps provided to setup and run docker-compose, and it seems every time i do, it's saying 
`cp: cannot create directory '/shared/media': No such file or directory`

Then further down i get a bunch of other errors. 
`Error: Failed to prepare seahub avatars dir: [Errno 2] No such file or directory: '/opt/seafile/seafile-server-7.1.9/seahub/media/avatars'
ln: failed to create symbolic link '/shared/media': No such file or directory
mkdir: cannot create directory '/shared/seahub-data/custom': No such file or directory
ln: failed to create symbolic link '/shared/media': No such file or directory
mv: cannot move './conf' to '/shared/conf': No such file or directory
mv: cannot move './ccnet' to '/shared/ccnet': No such file or directory
mv: cannot stat './seafile-data': No such file or directory
mv: cannot move './seahub-data' to '/shared/seahub-data': No such file or directory
mkdir: cannot create directory '/shared/logs': No such file or directory`

Am i missing something? I tried changing the Volume directory locations, and it seems to still happen.

**Comment by ChatDeBlofeld** [comment]
Yep, it turns out I messed up something with the permissions. 🤔

As a temporary fix, you should create the volume directory **before** running the compose command and giving it the UID/GID 1000.
