### ISSUE TITLE
/seafhttp 500 error

### ISSUE THREAD

**Issue by plant7403** [ChatDeBlofeld/seafile-arm-docker#8]
Hi, firstly I want to say thank you to the author for doing this work of keeping seafile available for arm64
Everything runs well except that seafhttp is showing 500 error for me, therefore no files downloading from the Android app
I run the testing configuration because I'm using cloudflared for tunneling
Logs show no info about seafhttp, what can be the problem?
Thank you

**Comment by ChatDeBlofeld** [comment]
Hi,
Honestly I've never run a Cloudflare service so this is a bit beyond me.

> Logs show no info about seafhttp

Which logs ? Seafile's ? Nginx's ?

My guess is there is something wrong with Nginx whose you can display error logs with:
```
docker exec <nginx_containter> cat /var/log/nginx/seafhttp.error.log
```

**Comment by plant7403** [comment]
```
2021/08/01 03:16:22 [error] 25#25: *110 the rewritten URI has a zero length, client
: 172.25.0.1, server: sea.vimc.me, request: "GET /seafhttp HTTP/1.1", host: "cloud.my.website"
```
There are many errors like this
Maybe it should be like that for just /seafhttp, but file downloading from android app doesn't work anyway

**Comment by ChatDeBlofeld** [comment]
<s>Seems legit since your not supposed to do a `GET` on  `/seafhttp` directly.</s> Ok haven't refresh the page.

What happens when you hit the `Download` button from the web interface ?

![image](https://user-images.githubusercontent.com/42017800/127774558-8c3b0d9e-8f90-453c-8ac8-0202ace7eb03.png)

**Comment by plant7403** [comment]
> Seems legit since your not supposed to do a GET on /seafhttp directly.

Ah, my guess was incorrect then

> What happens when you hit the Download button from the web interface ?

Everything works through the web interface
I get the problem in the android app (and I suppose, but didn't try, the desktop client)

**Comment by plant7403** [comment]
Solved, the problem was in ENABLE_TLS
I thought this variable was just about letsencrypt cert, but this option tells seafile which links to generate http or https
Seems android client is strict to those links (not just upgrading to https)

**Comment by ChatDeBlofeld** [comment]
Ok great, I was just writing I wiresharked the android traffic and saw absolutely nothing unexpected about it. 😆

Good point to know though, thanks for sharing your solution.
